PRAGMA foreign_keys = ON;
CREATE TABLE schools(id TEXT PRIMARY KEY, name TEXT NOT NULL);
INSERT INTO schools VALUES ('school-1','Colegio 1'),('school-2','Colegio 2'),('school-3','Colegio 3');
CREATE TABLE users(id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('superadmin','admin','operator','viewer')), school_ids TEXT NOT NULL DEFAULT '[]', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE sessions(token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE auth_attempts(id TEXT PRIMARY KEY, ip TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX auth_attempts_ip ON auth_attempts(ip,at);
CREATE TABLE settings(id INTEGER PRIMARY KEY CHECK(id=1), data TEXT NOT NULL);
INSERT INTO settings VALUES (1,'{"name":"PeloApp","color":"#315ded","font":"system","logo":"","footer":"Gracias por confiar en nosotros."}');
CREATE TABLE products(id TEXT PRIMARY KEY, name TEXT NOT NULL, price INTEGER NOT NULL CHECK(price > 0), version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE price_history(id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), price INTEGER NOT NULL, actor TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE clients(id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL, contact TEXT NOT NULL DEFAULT '', school_id TEXT NOT NULL REFERENCES schools(id), mode TEXT NOT NULL CHECK(mode IN ('original','current')), credit INTEGER NOT NULL DEFAULT 0 CHECK(credit>=0), version INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX clients_school ON clients(school_id,name);
CREATE TABLE events(id TEXT PRIMARY KEY, client_id TEXT NOT NULL REFERENCES clients(id), version INTEGER NOT NULL, kind TEXT NOT NULL, data TEXT NOT NULL, actor TEXT NOT NULL REFERENCES users(id), request_hash TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(client_id,version));
CREATE INDEX events_client ON events(client_id,version);
CREATE TABLE charges(id TEXT PRIMARY KEY, client_id TEXT NOT NULL REFERENCES clients(id), product_id TEXT REFERENCES products(id), description TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), unit_price INTEGER NOT NULL CHECK(unit_price>0), remaining INTEGER NOT NULL CHECK(remaining>=0), occurred_on TEXT NOT NULL, event_id TEXT NOT NULL REFERENCES events(id));
CREATE INDEX charges_client ON charges(client_id,occurred_on,id);
CREATE TABLE audit(id TEXT PRIMARY KEY, actor TEXT REFERENCES users(id), action TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL);
