ALTER TABLE schools ADD COLUMN logo TEXT NOT NULL DEFAULT '';
ALTER TABLE schools ADD COLUMN color TEXT NOT NULL DEFAULT '#315ded';
ALTER TABLE clients ADD COLUMN notes TEXT NOT NULL DEFAULT '';
CREATE TABLE catalog_events(id TEXT PRIMARY KEY, version INTEGER NOT NULL UNIQUE, actor TEXT NOT NULL REFERENCES users(id), request_hash TEXT NOT NULL, created_at TEXT NOT NULL);
